### ISSUE TITLE
No menu item for Ardour 5

### ISSUE THREAD

**Issue by rghvdberg** [KXStudio/Repository#44]
Mint 17.3 
updated ardour
(apt removed ardour4, I guess this is fine)
I have no menu item for ardour
rebooted
no menu item
copied /usr/share/applications/ardour.desktop to ~/.local/share/applications/
logged out and in
no menu item
I can run it from the terminal and via ALT-F2

**Comment by falkTX** [comment]
should be fixed, please confirm

**Comment by Houston4444** [comment]
Not fixed yet in gcc5 repos. (we can see that in ardour-v5/ardour.desktop

Another thing that would be nice is to have icons on ardour session files.
for that, just copy these files (in attachment or in source ardour/share/icons/) to the ardour-v5/debian directory and modify ardour.install adding these lines :
debian/application-x-ardour_16px.png     usr/share/icons/hicolor/16x16/apps
debian/application-x-ardour_22px.png     usr/share/icons/hicolor/22x22/apps
debian/application-x-ardour_32px.png     usr/share/icons/hicolor/32x32/apps
debian/application-x-ardour_48px.png     usr/share/icons/hicolor/48x48/apps


![application-x-ardour_16px](https://cloud.githubusercontent.com/assets/3808689/18815373/fe16bf3c-832e-11e6-8462-5eb6fd291c15.png)
![application-x-ardour_22px](https://cloud.githubusercontent.com/assets/3808689/18815374/fe17b8a6-832e-11e6-8d47-6cb8ade9123d.png)
![application-x-ardour_32px](https://cloud.githubusercontent.com/assets/3808689/18815371/fe15800e-832e-11e6-862b-8d6a646554a3.png)
![application-x-ardour_48px](https://cloud.githubusercontent.com/assets/3808689/18815372/fe1631c0-832e-11e6-8e02-41b4b9764985.png)

**Comment by falkTX** [comment]
You're right, sorry.
I fixed the desktop file for ardour non-gcc5 but not for gcc5 build.
https://github.com/KXStudio/Repository/blob/master/source/ardour-v5/debian/ardour.desktop

Will push an update next week.
The tip about the session files is a good one, thanks.

**Comment by falkTX** [comment]
Fixed now.
I added the icons, but not sure if they're working.

**Comment by Houston4444** [comment]
You're right for the icons, it doesn't works because I made two mistakes.
The first one is that all icons MUST be named application-x-ardour.png (and not application-x-ardour_32px.png ). 
The second one is that install path may not be 'apps' but 'mimetypes'.
So to make it works:
extract tar.gz in attachment to ardour-v5/debian

then modify the 4 lines in ardour.install to:

debian/mimeicons/16x16/application-x-ardour  usr/share/icons/hicolor/16x16/mimetypes
debian/mimeicons/22x22/application-x-ardour  usr/share/icons/hicolor/22x22/mimetypes
debian/mimeicons/32x32/application-x-ardour  usr/share/icons/hicolor/32x32/mimetypes
debian/mimeicons/48x48/application-x-ardour  usr/share/icons/hicolor/48x48/mimetypes

I just tested it in a new session and it works well ! Sorry for the mistakes.

[mimeicons.tar.gz](https://github.com/KXStudio/Repository/files/501859/mimeicons.tar.gz)
